
import { helloWorldExtractOutputsAndEvents, helloWorldHelper } from "./helloWorldHelper";
import {
  IEvent,
  WalletClient,
} from "@massalabs/massa-web3";
import { IBaseAccount } from "@massalabs/massa-web3/dist/esm/interfaces/IBaseAccount";


/**
 * This interface is used to represents the outputs of the SC call.
 *
 * @see outputs - The outputs of the SC call (optional)
 * @see events - The events emitted by the SC call (optional)
 */
export interface OperationOutputs {
  outputs?: any;
  events: IEvent[];
  error?: any;
}


export class C8ex2d7X8pkBlockchainCaller {
  private nodeRPC: string;

  public account: IBaseAccount;
  public coins: bigint;
  public fee: bigint = 0n;
  public maxGas: bigint = BigInt(4_294_967_295); // = max block gas limit


  constructor(account: IBaseAccount, coins: bigint, nodeRPC: string, fee?: bigint, maxGas?: bigint) {
    this.nodeRPC = nodeRPC;
    this.account = account;
    this.coins = coins;
    if(fee) this.fee = fee;
    if(maxGas) this.maxGas = maxGas;
  }

  /**
   * This method have been generated by the Massa Proto CLI.
   * It allows you to instantiate a new 8ex2d7X8pkBlockchainCaller object with the default values.
   *
   * @param {WalletClient} walletClient - The wallet client object to create the account from
   * 
   * @returns {Promise<C8ex2d7X8pkBlockchainCaller>} A promise that resolves to a new 8ex2d7X8pkBlockchainCaller object
   */
  static async newDefault(walletClient: WalletClient): Promise<C8ex2d7X8pkBlockchainCaller> {
    const nodeRPC = await walletClient.clientConfig.providers[0].url; 
    const account = await walletClient.getBaseAccount();
    if(!account) throw new Error("No account found in the wallet");
    const coins = 0n;
    return new C8ex2d7X8pkBlockchainCaller(account, coins, nodeRPC);
  }


  /**
   * This method have been generated by the Massa Proto CLI.
   * It allows you to call the "helloWorld" function of the
   * "AS12CvQGUaaSd933VNQGoQ8zja2Xvs6GhRJMDswLq2p8ex2d7X8pk" Smart Contract.
   *
   * @remarks
   * To work properly, you need to run 'npm install @protobuf-ts/plugin' in your project folder.
   * Otherwise, this caller will not work.
   *
   * @param {string} message - 
   *
   * @param {bigint} coins - The amount of Massa coins to send to the block creator
   *
   * @returns {Promise<OperationOutputs>} A promise that resolves to an object which contains the outputs and events from the call to helloWorld.
   */
  async helloWorld(
    message: string,
    coins?: bigint,
    fee?: bigint, 
    maxGas?:bigint
  ): Promise<OperationOutputs> {
    // Serialize the arguments
    const serializedArgs = helloWorldHelper.toBinary({
      message: message,
    });

    // Send the operation to the blockchain and retrieve its outputs
    if(!coins) coins = this.coins;
    if(!fee) fee = this.fee;
    if(!maxGas) maxGas = this.maxGas;

    return (
      await helloWorldExtractOutputsAndEvents(
        'AS12CvQGUaaSd933VNQGoQ8zja2Xvs6GhRJMDswLq2p8ex2d7X8pk',
        'helloWorld',
        serializedArgs,
        coins,
        'void',
        this.account,
        this.nodeRPC,
        fee,
        maxGas,
      )
    );
  }

  /**
  * This method have been generated by the Massa Proto CLI.
  * It allows you to update the amount of Massa coins to send to the block creator when calling the Smart Contract.
  */
 editCoins(coins: bigint) {
   this.coins = coins;
 }
}
