
/*****************IMPORTS GENERATED BY MASSA-PROTO-CLI*****************/

import {
  OperationOutputs,
} from "./8ex2d7X8pkCaller";
import { getEvents } from "./commonHelper";
import { IBaseAccount } from "@massalabs/massa-web3/dist/esm/interfaces/IBaseAccount";
import {
  IEvent,
  ICallData,
} from "@massalabs/massa-web3";


/*****************GENERATED BY PROTOC*****************/

// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "helloWorld.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message helloWorldHelper
 */
export interface helloWorldHelper {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class helloWorldHelper$Type extends MessageType<helloWorldHelper> {
    constructor() {
        super("helloWorldHelper", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<helloWorldHelper>): helloWorldHelper {
        const message = { message: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<helloWorldHelper>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: helloWorldHelper): helloWorldHelper {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: helloWorldHelper, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message helloWorldHelper
 */
export const helloWorldHelper = new helloWorldHelper$Type();



/*****************GENERATED BY MASSA-PROTO-CLI*****************/

const OUTPUTS_PREFIX = 'ResulthelloWorld:';

export async function helloWorldExtractOutputsAndEvents(
  contractAddress: string,
  functionName: string,
  args: Uint8Array,
  coins: bigint,
  returnType: string,
  account: IBaseAccount,
  nodeUrl: string,
  fee = 0n,
  maxGas = BigInt(4_294_967_295), // = max block gas limit
): Promise<OperationOutputs> {

  let events: IEvent[] = [];

  // try to call the Smart Contract
  try{
    events = await getEvents(
      { operationId:
        await account.callSmartContract(
          {
            fee: fee,
            maxGas: maxGas,
            coins: coins,
            targetAddress: contractAddress,
            functionName: functionName,
            parameter: Array.from(args),
          } as ICallData,
        ),
      },
      nodeUrl,
    )
  }
  catch (err) {
    console.log("Error while calling the Smart Contract: " + err);
    return {
      events: events,
      error: err,
    } as OperationOutputs;
  }

  // if the call is successful, retrieve the outputs from the events
  let rawOutput: string | null = null;
  for (let event of events) {
    if (event.data.slice(0, OUTPUTS_PREFIX.length) == OUTPUTS_PREFIX) {
      rawOutput = event.data.slice(OUTPUTS_PREFIX.length);
      // remove the event from the list
      events.splice(events.indexOf(event), 1);
      break;
    }
  }

  // check the output and return the result
  if (rawOutput === null && returnType !== 'void') {
    const detectedEventsData = events.map((e) => e.data);
    throw new Error(
      'Output expected but not found. Events detected:\n' + '[ ' + detectedEventsData.join(' ]\n[ ') + ' ]',
    );
  }
  if(rawOutput === null && returnType === 'void') {
    return{
      events: events,
    };
  }
  if(rawOutput !== null && returnType !== 'void') {
    
    return {
      events: events,
    } as OperationOutputs;
  }
  throw new Error('helloWorldCaller: Unexpected error');
}


