name: Npm next publish

on:
  push:
    branches: [next]

jobs:
  test:
    uses: ./.github/workflows/massaStation-e2e-tests.yml
    secrets: inherit

  massa-web3-integration-test:
    uses: ./.github/workflows/massa-web3-integration.yml

  publish-npm-next:

    runs-on: ubuntu-latest
    needs: [test, massa-web3-integration-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: 'npm'
        
      - name: Publish next version to npm
        run: ./scripts/publish-next.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}


